default:
  golem_name: peskas.mozambique.portal
  golem_version: 0.0.0.9000
  app_prod: no
  deployment:
    google_key: !expr readLines('auth/gcp-sa-peskas_ingestion-key.json')
  kobo:
    asset_id: !expr readLines('auth/asset_id')
    token: !expr readLines('auth/kobo_token')
  storage:
    mongodb:
      connection_string: !expr readLines('auth/mongodb-connection-string')
      database_name: pipeline
      collection_name:
        validated: validated
        preprocessed: preprocessed
  mapbox_token: !expr readLines('auth/mapbox-token')
  validation:
    user: !expr readLines('auth/username')
    pass: !expr readLines('auth/password')

production:
  app_prod: yes
  deployment:
    google_key: !expr Sys.getenv('GCP_SA_KEY')
  kobo:
    asset_id: !expr Sys.getenv('ASSET_ID')
    token: !expr Sys.getenv('KOBO_TOKEN')
  storage:
    mongodb:
      connection_string: !expr Sys.getenv('MONGODB_CONNECTION_STRING')
  mapbox_token: !expr Sys.getenv('MAPBOX-TOKEN')
  validation:
    user: !expr Sys.getenv('VAL_USER')
    pass: !expr Sys.getenv('VAL_PASS')


dev:
  golem_wd: !expr golem::pkg_path()
